import { IStaticGridGetDataParams } from "../../../util/entity";

const EMPTY_DATA_SET = [
	{
		data: [{ f1: "f1" }, { f2: "f2" }, { f3: "f3" }],
		res: false
	},
	{
		data: [],
		res: true
	},
	{
		data: null,
		res: true
	}
];

const SIMPLE_GET_DATA_PARAMS: IStaticGridGetDataParams = {
	url: "url",
	params: [],
	transformMeta: () => [],
	transformData: () => [],
	errorActions:
	 () => []
};

const DATA_RESULT = [
	{
		"id": 5,
		"name": "123",
		"default": false,
		"project": "Evergreen",
		"type": "All",
		"outcome": "In Progress, Success",
		"submitted": "Last 30 days",
		"user": "All"
	},
	{
		"id": 7,
		"name": "2",
		"default": false,
		"project": "Evergreen",
		"type": "All",
		"outcome": "In Progress, Submitted, Success",
		"submitted": "Last 30 days",
		"user": "Admin"
	}
];

const METADATA_RESULT = [
	{
		"link": null,
		"tags": 0,
		"friendlyName": "Name",
		"columnName": "name",
		"category": "",
		"sortingType": "String",
		"filterType": "String",
		"visible": true,
		"customUiTransformation": "",
		"url": null,
		"urlParams": null,
		"alternativeUrl": null,
		"checkParam": null,
		"alternativeUrlParams": null,
		"key": null,
		"type": null,
		"customUiTransformationField": null,
		"filterOptions": null,
		"pinned": false,
		"notTransferable": false,
		"userInput": false,
		"lockVisible": false,
		"editPermissionsValidator": null,
		"editPermissionsValidatorParameters": null,
		"readonlyCustomUiTransformation": null,
		"permission": null,
		"permissionCanEdit": null,
		"permissionCanView": null,
		"visibilityValidator": null,
		"visibilityValidatorParameters": null,
		"isObjectKey": false,
		"rowTooltip": null,
		"rowDisabled": null,
		"permissionDeniedMessage": null
	},
	{
		"link": null,
		"tags": 0,
		"friendlyName": "Default",
		"columnName": "default",
		"category": "",
		"sortingType": "String",
		"filterType": "Multiselect",
		"visible": true,
		"customUiTransformation": "BooleanImage",
		"url": null,
		"urlParams": null,
		"alternativeUrl": null,
		"checkParam": null,
		"alternativeUrlParams": null,
		"key": null,
		"type": null,
		"customUiTransformationField": null,
		"filterOptions": null,
		"pinned": false,
		"notTransferable": false,
		"userInput": false,
		"lockVisible": false,
		"editPermissionsValidator": null,
		"editPermissionsValidatorParameters": null,
		"readonlyCustomUiTransformation": null,
		"permission": null,
		"permissionCanEdit": null,
		"permissionCanView": null,
		"visibilityValidator": null,
		"visibilityValidatorParameters": null,
		"isObjectKey": false,
		"rowTooltip": null,
		"rowDisabled": null,
		"permissionDeniedMessage": null
	},
	{
		"link": null,
		"tags": 0,
		"friendlyName": "Project",
		"columnName": "project",
		"category": "",
		"sortingType": "String",
		"filterType": "Multiselect",
		"visible": true,
		"customUiTransformation": "",
		"url": null,
		"urlParams": null,
		"alternativeUrl": null,
		"checkParam": null,
		"alternativeUrlParams": null,
		"key": null,
		"type": null,
		"customUiTransformationField": null,
		"filterOptions": null,
		"pinned": false,
		"notTransferable": false,
		"userInput": false,
		"lockVisible": false,
		"editPermissionsValidator": null,
		"editPermissionsValidatorParameters": null,
		"readonlyCustomUiTransformation": null,
		"permission": null,
		"permissionCanEdit": null,
		"permissionCanView": null,
		"visibilityValidator": null,
		"visibilityValidatorParameters": null,
		"isObjectKey": false,
		"rowTooltip": null,
		"rowDisabled": null,
		"permissionDeniedMessage": null
	},
	{
		"link": null,
		"tags": 0,
		"friendlyName": "Type",
		"columnName": "type",
		"category": "",
		"sortingType": "String",
		"filterType": "String",
		"visible": true,
		"customUiTransformation": "",
		"url": null,
		"urlParams": null,
		"alternativeUrl": null,
		"checkParam": null,
		"alternativeUrlParams": null,
		"key": null,
		"type": null,
		"customUiTransformationField": null,
		"filterOptions": null,
		"pinned": false,
		"notTransferable": false,
		"userInput": false,
		"lockVisible": false,
		"editPermissionsValidator": null,
		"editPermissionsValidatorParameters": null,
		"readonlyCustomUiTransformation": null,
		"permission": null,
		"permissionCanEdit": null,
		"permissionCanView": null,
		"visibilityValidator": null,
		"visibilityValidatorParameters": null,
		"isObjectKey": false,
		"rowTooltip": null,
		"rowDisabled": null,
		"permissionDeniedMessage": null
	},
	{
		"link": null,
		"tags": 0,
		"friendlyName": "Outcome",
		"columnName": "outcome",
		"category": "",
		"sortingType": "String",
		"filterType": "String",
		"visible": true,
		"customUiTransformation": "",
		"url": null,
		"urlParams": null,
		"alternativeUrl": null,
		"checkParam": null,
		"alternativeUrlParams": null,
		"key": null,
		"type": null,
		"customUiTransformationField": null,
		"filterOptions": null,
		"pinned": false,
		"notTransferable": false,
		"userInput": false,
		"lockVisible": false,
		"editPermissionsValidator": null,
		"editPermissionsValidatorParameters": null,
		"readonlyCustomUiTransformation": null,
		"permission": null,
		"permissionCanEdit": null,
		"permissionCanView": null,
		"visibilityValidator": null,
		"visibilityValidatorParameters": null,
		"isObjectKey": false,
		"rowTooltip": null,
		"rowDisabled": null,
		"permissionDeniedMessage": null
	},
	{
		"link": null,
		"tags": 0,
		"friendlyName": "Submitted",
		"columnName": "submitted",
		"category": "",
		"sortingType": "String",
		"filterType": "String",
		"visible": true,
		"customUiTransformation": "",
		"url": null,
		"urlParams": null,
		"alternativeUrl": null,
		"checkParam": null,
		"alternativeUrlParams": null,
		"key": null,
		"type": null,
		"customUiTransformationField": null,
		"filterOptions": null,
		"pinned": false,
		"notTransferable": false,
		"userInput": false,
		"lockVisible": false,
		"editPermissionsValidator": null,
		"editPermissionsValidatorParameters": null,
		"readonlyCustomUiTransformation": null,
		"permission": null,
		"permissionCanEdit": null,
		"permissionCanView": null,
		"visibilityValidator": null,
		"visibilityValidatorParameters": null,
		"isObjectKey": false,
		"rowTooltip": null,
		"rowDisabled": null,
		"permissionDeniedMessage": null
	},
	{
		"link": null,
		"tags": 0,
		"friendlyName": "User",
		"columnName": "user",
		"category": "",
		"sortingType": "String",
		"filterType": "String",
		"visible": true,
		"customUiTransformation": "",
		"url": null,
		"urlParams": null,
		"alternativeUrl": null,
		"checkParam": null,
		"alternativeUrlParams": null,
		"key": null,
		"type": null,
		"customUiTransformationField": null,
		"filterOptions": null,
		"pinned": false,
		"notTransferable": false,
		"userInput": false,
		"lockVisible": false,
		"editPermissionsValidator": null,
		"editPermissionsValidatorParameters": null,
		"readonlyCustomUiTransformation": null,
		"permission": null,
		"permissionCanEdit": null,
		"permissionCanView": null,
		"visibilityValidator": null,
		"visibilityValidatorParameters": null,
		"isObjectKey": false,
		"rowTooltip": null,
		"rowDisabled": null,
		"permissionDeniedMessage": null
	}
];

const DATA_SET = {
	"uIType": "htmltable",
	"metadata": METADATA_RESULT,
	"results": DATA_RESULT
};

export {
	EMPTY_DATA_SET,
	SIMPLE_GET_DATA_PARAMS,
	DATA_RESULT,
	METADATA_RESULT,
	DATA_SET
};
